alertmanagerFiles:
  alertmanager.yml:
    global:
      slack_api_url: "" # secret
    receivers:
      - name: default-receiver
        slack_configs:
          - send_resolved: true

extraScrapeConfigs: |
  - job_name: 'prometheus-blackbox-exporter'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://sbtechcoop.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: prom-blackbox-exporter-prometheus-blackbox-exporter:9115

serverFiles:
  alerts:
    groups:
    - name: alert.rules
      rules:
      - alert: EndPointDown
        expr: probe_success == 0
        for: 5m
        labels:
          severity: "critical"
        annotations:
          summary: "Endpoint {{ $labels.instance }} down"
